import { launchBrowser } from './browser.js';
import { createServer } from 'vite';
import assert from 'node:assert/strict';
import { STORAGE_KEY } from '../src/leaderboard.js';

const server = await createServer({ server: { port: 0 } });
await server.listen();
let browser;
try {
  browser = await launchBrowser();
  const page = await browser.newPage({ reducedMotion: 'reduce', viewport: { width: 320, height: 568 } });
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(`http://localhost:${server.httpServer.address().port}`);
  await page.evaluate(async () => {
    window.state = (await import('/src/state.js')).gameState;
    Math.random = () => 22.1 / 24; // APPLE
    const now = Date.now;
    window.offset = 0;
    Date.now = () => now() + window.offset;
  });
  const state = () => page.evaluate(() => JSON.parse(JSON.stringify(window.state)));
  const saved = () => page.evaluate((key) => JSON.parse(localStorage.getItem(key) || '[]'), STORAGE_KEY);
  const guess = async (word) => {
    await page.locator('#game-title').focus();
    await page.keyboard.type(word.toLowerCase());
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => !window.state.round.revealing);
  };
  await page.getByLabel('Enter your name', { exact: true }).fill('Hint player');
  await page.getByLabel('Enter your name', { exact: true }).press('Enter');
  await page.evaluate(() => { Math.random = () => .25; });
  await page.locator('#hint-button').focus();
  await page.keyboard.press('Enter'); // Native focused button activation.
  assert.equal(await page.locator('#hint-strip').innerText(), '_ P _ _ _');
  assert.equal((await state()).round.currentGuess, '');
  await guess('ALLEY');
  await page.evaluate(() => { Math.random = () => 0; window.offset += 65000; document.dispatchEvent(new Event('visibilitychange')); });
  await page.locator('#hint-button').click();
  assert.equal(await page.locator('#hint-strip').innerText(), '_ P P _ _');
  await page.locator('#hint-button').click();
  assert.equal(await page.locator('#hint-button').innerText(), 'Hint (3/3)');
  assert.ok(await page.locator('#hint-button').isDisabled());
  assert.equal((await state()).round.guesses.length, 1);
  assert.equal((await state()).round.completedAt, null);
  assert.ok((await page.locator('#elapsed-time').innerText()).startsWith('1:'));
  const old = (await state()).round;
  page.once('dialog', (dialog) => { assert.equal(dialog.message(), 'Restart this word?'); return dialog.dismiss(); });
  await page.locator('#retry-button').click();
  assert.equal((await state()).round.id, old.id);
  page.once('dialog', (dialog) => dialog.accept());
  await page.locator('#retry-button').focus();
  await page.keyboard.press('Enter');
  const fresh = (await state()).round;
  assert.notEqual(fresh.id, old.id);
  assert.deepEqual(fresh.word, old.word);
  assert.equal(fresh.playerName, old.playerName);
  assert.equal(fresh.isRetry, true);
  assert.equal(fresh.hintsUsed, 0);
  assert.deepEqual(fresh.hintPositions, []);
  assert.deepEqual(fresh.guesses, []);
  assert.deepEqual(fresh.keys, {});
  assert.equal(fresh.currentGuess, '');
  assert.ok(fresh.startedAt - old.startedAt >= 65000);
  assert.equal(await page.locator('#elapsed-time').innerText(), '0:00');
  assert.equal(await page.locator('#hint-strip').innerText(), '_ _ _ _ _');
  assert.equal(await page.locator('#keyboard [data-feedback]').count(), 0);
  assert.equal((await saved()).length, 0);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.locator('#game-title').focus();
  await page.keyboard.type('alley');
  await page.keyboard.press('Enter');
  assert.ok(await page.locator('#hint-button').isDisabled());
  assert.ok(await page.locator('#retry-button').isDisabled());
  await page.waitForFunction(() => !window.state.round.revealing);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await guess('APPLE');
  await page.waitForSelector('#result:not([hidden])');
  assert.equal(await page.locator('#result-badge').innerText(), 'Practice');
  assert.equal(await page.locator('#result-rank').innerText(), 'Practice');
  assert.equal(await page.locator('#result-leaderboard .top-five').count(), 0);
  const completed = (await saved())[0];
  await page.locator('#result-retry').click();
  assert.deepEqual((await saved())[0], completed);
  assert.equal((await state()).completedResult.id, completed.id);
  for (let i = 0; i < 6; i++) await guess('HOUSE');
  await page.waitForSelector('#result:not([hidden])');
  assert.equal(await page.locator('#result-rank').innerText(), 'Practice · Not solved');
  assert.equal((await saved()).length, 2);
  await page.keyboard.press('Enter');
  assert.equal((await saved()).length, 2);
  await page.locator('#next-player').click();
  await page.getByLabel('Enter your name', { exact: true }).fill('Assisted player');
  await page.getByLabel('Enter your name', { exact: true }).press('Enter');
  await page.locator('#hint-button').click();
  await guess('STACK');
  await page.waitForSelector('#result:not([hidden])');
  assert.equal(await page.locator('#result-badge').innerText(), 'Assisted');
  assert.equal(await page.locator('#result-rank').innerText(), 'Assisted');
  assert.equal((await saved()).length, 3);
  assert.equal((await saved())[2].hintsUsed, 1);
  assert.equal((await saved())[2].isRetry, false);
  assert.equal(await page.locator('#result-leaderboard .top-five').count(), 0);
  await page.locator('#next-player').click();
  await page.getByLabel('Enter your name', { exact: true }).fill('Assisted loss');
  await page.getByLabel('Enter your name', { exact: true }).press('Enter');
  await page.locator('#hint-button').click();
  const bounds = await page.locator('#keyboard').boundingBox();
  assert.ok(bounds.y + bounds.height <= 568);
  for (let i = 0; i < 6; i++) await guess('HOUSE');
  await page.waitForSelector('#result:not([hidden])');
  assert.equal(await page.locator('#result-rank').innerText(), 'Assisted · Not solved');
  assert.equal(await page.locator('#result-badge').innerText(), 'Assisted');
  assert.equal(await page.locator('#result-leaderboard .current-attempt td').first().innerText(), 'Assisted · Not solved');
  assert.equal((await saved()).length, 4);
  assert.equal(new Set((await saved()).map(({ id }) => id)).size, 4);
  await page.screenshot({ path: '.checks/assisted-result-320.png' });
  assert.deepEqual(errors, []);
  console.log('PASS: position-specific hints, green exclusions, three-hint limit, focused buttons, reveal locks, continued timer, retry cancel/reset, retained results, practice losses, assisted eligibility and unique saves.');
} finally {
  await browser?.close();
  await server.close();
}
