import { launchBrowser, stubWordRandom } from './browser.js';
import { createServer } from 'vite';
import assert from 'node:assert/strict';
import { STORAGE_KEY } from '../src/leaderboard.js';

const server = await createServer({ server: { port: 0 } });
await server.listen();
let browser;
try {
  browser = await launchBrowser();
  const page = await browser.newPage({ reducedMotion: 'reduce', viewport: { width: 320, height: 568 } });
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(`http://localhost:${server.httpServer.address().port}`);
  await page.evaluate(async () => {
    window.state = (await import('/src/state.js')).gameState;
    const now = Date.now;
    window.offset = 0;
    Date.now = () => now() + window.offset;
  });
  await page.evaluate(stubWordRandom, 22); // APPLE
  const state = () => page.evaluate(() => JSON.parse(JSON.stringify(window.state)));
  const saved = () => page.evaluate((key) => JSON.parse(localStorage.getItem(key) || '[]'), STORAGE_KEY);
  const guess = async (word) => {
    await page.locator('#game-title').focus();
    await page.keyboard.type(word.toLowerCase());
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => !window.state.round.revealing);
  };
  await page.getByLabel('Enter your name', { exact: true }).fill('Hint player');
  await page.getByLabel('Enter your name', { exact: true }).press('Enter');
  await page.evaluate(() => { Math.random = () => .25; });
  await page.locator('#hint-button').focus();
  await page.keyboard.press('Enter'); // Native focused button activation.
  assert.equal(await page.locator('#hint-strip').innerText(), '_ P _ _ _');
  assert.equal((await state()).round.currentGuess, '');
  await guess('ALLEY');
  await page.evaluate(() => { Math.random = () => 0; window.offset += 65000; document.dispatchEvent(new Event('visibilitychange')); });
  await page.locator('#hint-button').click();
  assert.equal(await page.locator('#hint-strip').innerText(), '_ P P _ _');
  await page.locator('#hint-button').click();
  assert.equal(await page.locator('#hint-button').innerText(), 'Hint (3/3)');
  assert.ok(await page.locator('#hint-button').isDisabled());
  assert.equal((await state()).round.guesses.length, 1);
  assert.equal((await state()).round.completedAt, null);
  assert.ok((await page.locator('#elapsed-time').innerText()).startsWith('1:'));
  const old = (await state()).round;
  page.once('dialog', (dialog) => { assert.equal(dialog.message(), 'Start a new round?'); return dialog.dismiss(); });
  await page.locator('#retry-button').click();
  assert.equal((await state()).round.id, old.id);
  await page.evaluate(stubWordRandom, 0);
  page.once('dialog', (dialog) => dialog.accept());
  await page.locator('#retry-button').focus();
  await page.keyboard.press('Enter');
  const fresh = (await state()).round;
  assert.notEqual(fresh.id, old.id);
  assert.notEqual(fresh.word.answer, old.word.answer);
  assert.equal(await page.locator('#category-hint').innerText(), `Hint: ${fresh.word.category}`);
  assert.equal((await state()).completedResult, null);
  assert.equal(await page.evaluate(() => window.wordRandomCalls), 1);
  assert.equal(fresh.playerName, old.playerName);
  assert.equal(fresh.hintsUsed, 0);
  assert.deepEqual(fresh.hintPositions, []);
  assert.deepEqual(fresh.guesses, []);
  assert.deepEqual(fresh.keys, {});
  assert.equal(fresh.currentGuess, '');
  assert.ok(fresh.startedAt - old.startedAt >= 65000);
  assert.equal(await page.locator('#elapsed-time').innerText(), '0:00');
  assert.equal(await page.locator('#hint-strip').innerText(), '_ _ _ _ _');
  assert.equal(await page.locator('#keyboard [data-feedback]').count(), 0);
  assert.equal((await saved()).length, 0);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.locator('#game-title').focus();
  await page.keyboard.type('alley');
  await page.keyboard.press('Enter');
  assert.ok(await page.locator('#hint-button').isDisabled());
  assert.ok(await page.locator('#retry-button').isDisabled());
  await page.waitForFunction(() => !window.state.round.revealing);
  assert.equal((await saved()).length, 0); // A guess is not a completed try.
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await guess(fresh.word.answer);
  await page.waitForSelector('#result:not([hidden])');
  assert.ok(await page.locator('#result-badge').isHidden());
  assert.equal(await page.locator('#result-rank').innerText(), 'Rank 1');
  assert.equal(await page.locator('#result-leaderboard .top-five').count(), 1);
  assert.equal(await page.locator('#result-leaderboard .assisted-badge').count(), 0);
  const completed = (await saved())[0];
  await page.locator('#result-retry').click();
  assert.deepEqual((await saved())[0], completed);
  assert.equal((await state()).completedResult, null);
  assert.notEqual((await state()).round.word.answer, completed.word);
  for (let i = 0; i < 6; i++) await guess('HOUSE');
  await page.waitForSelector('#result:not([hidden])');
  assert.equal(await page.locator('#result-rank').innerText(), 'Not solved');
  assert.equal((await saved()).length, 2);
  assert.equal((await saved())[1].playerName, completed.playerName);
  await page.keyboard.press('Enter');
  assert.equal((await saved()).length, 2);
  await page.locator('#next-player').click();
  await page.getByLabel('Enter your name', { exact: true }).fill('Assisted player');
  await page.getByLabel('Enter your name', { exact: true }).press('Enter');
  await page.locator('#hint-button').click();
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.locator('#game-title').focus();
  await page.keyboard.type('stack');
  await page.evaluate(() => {
    const enter = document.querySelector('[data-key="Enter"]');
    enter.click();
    enter.click();
    enter.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  });
  // The completed round is saved before animation; repeated submission adds nothing.
  assert.equal((await saved()).length, 3);
  await page.waitForSelector('#result:not([hidden])');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('#result-badge').innerText(), 'Assisted');
  assert.equal(await page.locator('#result-rank').innerText(), 'Rank 1');
  assert.equal((await saved()).length, 3);
  assert.equal((await saved())[2].hintsUsed, 1);
  assert.equal(await page.locator('#result-leaderboard .top-five').count(), 2);
  assert.equal(await page.locator('#result-leaderboard .current-attempt td:nth-child(2) .assisted-badge').innerText(), 'Assisted');
  await page.locator('#next-player').click();
  await page.getByLabel('Enter your name', { exact: true }).fill('Assisted loss');
  await page.getByLabel('Enter your name', { exact: true }).press('Enter');
  await page.locator('#hint-button').click();
  const bounds = await page.locator('#keyboard').boundingBox();
  assert.ok(bounds.y + bounds.height <= 568);
  for (let i = 0; i < 6; i++) await guess('HOUSE');
  await page.waitForSelector('#result:not([hidden])');
  assert.equal(await page.locator('#result-rank').innerText(), 'Not solved');
  assert.equal(await page.locator('#result-badge').innerText(), 'Assisted');
  assert.equal(await page.locator('#result-leaderboard .current-attempt td').first().innerText(), 'Not solved');
  assert.equal(await page.locator('#result-leaderboard .current-attempt td:nth-child(2) .assisted-badge').innerText(), 'Assisted');
  assert.equal((await saved()).length, 4);
  assert.equal(new Set((await saved()).map(({ id }) => id)).size, 4);
  await page.screenshot({ path: '.checks/assisted-result-320.png' });
  const beforeRefresh = await saved();
  await page.reload();
  await page.locator('#leaderboard-button').click();
  assert.deepEqual(await saved(), beforeRefresh);
  assert.equal(await page.locator('#full-leaderboard tbody tr').count(), 4);
  assert.equal(await page.locator('#full-leaderboard .assisted-badge').count(), 2);
  assert.equal(await page.locator('#full-leaderboard .top-five .assisted-badge').count(), 1);
  assert.equal(await page.locator('#full-leaderboard .top-five').count(), 2);
  assert.doesNotMatch(await page.locator('body').textContent(), /practice/i);
  await page.screenshot({ path: '.checks/assisted-leaderboard-320.png' });
  await page.reload();
  await page.locator('#leaderboard-button').click();
  assert.deepEqual(await saved(), beforeRefresh);
  await page.locator('#leaderboard [data-back]').click();
  await page.locator('#player-name').fill('Assisted player');
  await page.locator('#player-name').press('Enter');
  assert.equal(await page.locator('#hint-button').innerText(), 'Hint (0/3)');
  assert.equal(await page.locator('#hint-strip').innerText(), '_ _ _ _ _');
  page.once('dialog', (dialog) => dialog.accept());
  await page.locator('#game [data-back]').click();
  assert.deepEqual(await saved(), beforeRefresh);
  assert.deepEqual(errors, []);
  console.log('PASS: hints, reveal locks, retry reset/counts, repeated names, assisted rankings/badges after refresh, losses, double submission and unique saves.');
} finally {
  await browser?.close();
  await server.close();
}
